@startuml
skinparam rectangle {
  RoundCorner 25
}
skinparam ArrowColor #333333

rectangle "EQUIPO DEL USUARIO\n\ncomputador o teléfono de la sede\n\nLo que se ejecuta aquí: un navegador web\n(hoy Swagger UI y la interfaz Angular)" as equipo #DDDDDD

rectangle "SERVIDOR DE APLICACIONES\n\nlo que se ejecuta aquí:\nJava con el backend empaquetado\nbackend_gestion_academica_vergel.jar\nPuerto 8080" as app #A9D1F5

rectangle "SERVIDOR DE BASE DE DATOS\n\nLo que se ejecuta aquí:\nPostgreSQL\nCon las 13 tablas del sistema" as db #F5F0A9

equipo -down-> app : Internet o Red Local\npeticiones HTTPS en\nformato JSON
app -down-> db : conexión JDBC\nconsultas SQL

@enduml
